name: Build and Package App

on:
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - 'icon.png'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and package app
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "/workspaces/PyQR/icon.ico" --add-data "/workspaces/PyQR/icon.icns:.icon.icns" --add-data "/workspaces/PyQR/icon.ico:.icon.ico" --add-data "/workspaces/PyQR/icon.png:.icon.png"  "/workspaces/PyQR/main.py"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: dist/main
